/**
 * NIRO
 * Please add description
 *
 * OpenAPI spec version: 0.1.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * status ok | ko.  See [Orange Recommendation](https://recommendations.innov.intraorange/designing-orange-api/#status-path)
 */
export type OrangeApiStatusValue = 'ok' | 'ko';

export const OrangeApiStatusValue = {
    Ok: 'ok' as OrangeApiStatusValue,
    Ko: 'ko' as OrangeApiStatusValue
};