/**
 * NIRO
 * Please add description
 *
 * OpenAPI spec version: 0.1.0_inProgress
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Milestone } from '../model/milestone';
import { MilestoneLite } from '../model/milestoneLite';
import { OrangeApiError } from '../model/orangeApiError';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MilestoneService {

    protected basePath = '/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * create milestone
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public milestoneCreate(body: MilestoneLite, observe?: 'body', reportProgress?: boolean): Observable<Milestone>;
    public milestoneCreate(body: MilestoneLite, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Milestone>>;
    public milestoneCreate(body: MilestoneLite, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Milestone>>;
    public milestoneCreate(body: MilestoneLite, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling milestoneCreate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json;charset=utf-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=utf-8'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Milestone>('post',`${this.basePath}/milestone`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * find milestone
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public milestoneFind(observe?: 'body', reportProgress?: boolean): Observable<Array<Milestone>>;
    public milestoneFind(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Milestone>>>;
    public milestoneFind(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Milestone>>>;
    public milestoneFind(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json;charset=utf-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Milestone>>('get',`${this.basePath}/milestone`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get milestone
     * 
     * @param milestoneId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public milestoneGet(milestoneId: string, observe?: 'body', reportProgress?: boolean): Observable<Milestone>;
    public milestoneGet(milestoneId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Milestone>>;
    public milestoneGet(milestoneId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Milestone>>;
    public milestoneGet(milestoneId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (milestoneId === null || milestoneId === undefined) {
            throw new Error('Required parameter milestoneId was null or undefined when calling milestoneGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json;charset=utf-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Milestone>('get',`${this.basePath}/milestone/${encodeURIComponent(String(milestoneId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update milestone
     * 
     * @param body 
     * @param milestoneId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public milestoneUpdate(body: Milestone, milestoneId: string, observe?: 'body', reportProgress?: boolean): Observable<Milestone>;
    public milestoneUpdate(body: Milestone, milestoneId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Milestone>>;
    public milestoneUpdate(body: Milestone, milestoneId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Milestone>>;
    public milestoneUpdate(body: Milestone, milestoneId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling milestoneUpdate.');
        }

        if (milestoneId === null || milestoneId === undefined) {
            throw new Error('Required parameter milestoneId was null or undefined when calling milestoneUpdate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json;charset=utf-8'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json;charset=utf-8'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Milestone>('put',`${this.basePath}/milestone/${encodeURIComponent(String(milestoneId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
